id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description:
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'status:waiting-for-author-feedback'
      - hasLabel:
          label: 'Status: No Recent Activity'
      - noActivitySince:
          days: 3
      actions:
      - closeIssue
    - description:
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'status:waiting-for-author-feedback'
      - noActivitySince:
          days: 4
      - isNotLabeledWith:
          label: 'Status: No Recent Activity'
      actions:
      - addLabel:
          label: 'Status: No Recent Activity'
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.
    - description:
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: 'Resolution: Duplicate'
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue
    eventResponderTasks:
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'status:waiting-for-author-feedback'
      - isOpen
      then:
      - addLabel:
          label: 'Needs: Attention :wave:'
      - removeLabel:
          label: 'status:waiting-for-author-feedback'
      description:
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description:
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: 'Status: No Recent Activity'
      then:
      - removeLabel:
          label: 'Status: No Recent Activity'
      description:
    - if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: WIP
      description:
onFailure:
onSuccess:
