# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in microsoft_kiota_abstractions.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', require: false

gem 'addressable', '~> 2.7', '>= 2.7.0'

gem 'iso8601', '~> 0.13.0'
