openapi: 3.0.0
info:
  title: Suno
  description: Create any song you want based on a description
  version: 1.0.0
  contact:
    email: ionutro@microsoft.com
  x-logo:
    url: https://w7.pngwing.com/pngs/208/848/png-transparent-musical-note-logo-clef-music-logo-design-other-text-musical-composition.png
  x-ai-description: Suno is a tool that can generate songs based on a description. The user provides a description of the song they want to create, and Suno generates the song lyrics. Suno is a fun and creative way to create songs for any occasion.
  x-legal-info-url": https://app.suno.ai/legal
  x-privacy-policy-url": https://app.suno.ai/privacy
paths:
  /createSong:
    post:
      summary: Create a song given the user preferences
      operationId: createSong
      x-ai-reasoning-instructions:
        - 'Is the user requesting to create a song which would warrant the "Parental Advisory Explicit Content" label (e.g., topics about sex, politics, violence, self-harm, hate speech, coercion, etc.)? If so, I **must** invoke withdraw() and end the conversation.'
        - "Is the user requesting to create a haiku, poem, lyric, tune, melody, jingle, verse, sonnet, or something other than a song? If so, I **must not** invoke createSong(**params)."
        - "Is the user requesting to create a song on a safe and innocuous topic? If so, invoke createSong(**params)."
        - "If createSong(**params) is invoked already in this turn, I **will** not invoke the same tool again."
        - "Here are the parameters"
        - "topic(string, required): The requested song description, e.g., a country song about Thanksgiving, in the user's language"
      x-ai-responding-instructions:
        - "The response to the user is generated asynchronously therefore I **SHOULD NOT** generate my own song or provide links or lyrics based on this tool's output. I can just let the user know their song will be available shortly and **stop responding** for that turn."
        - "I **should not** respond with either sample or full form of lyrics to the song because the song created by createSong(**params) is shown to the user directly along with the lyrics."
        - "If createSong(**params) was not invoked because the service was overloaded or the user reached their invocation limit, I **must** tell the user they can visit the https://app.suno.ai website to create more songs and display the link using Markdown syntax."
        - "I **shall** tell the user they can visit the https://app.suno.ai website to create more songs and display the link using Markdown syntax."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The requested song description, e.g., a country song about Thanksgiving
      responses:
        "200":
          description: A Song object
          content:
            application/json:
              schema:
                type: object
                properties:
                  lyrics:
                    type: string
                    description: The generated song
                  title:
                    type: string
                    description: The title of the song
