using System;
using System.IO;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;
using Kiota.Builder.Writers.Rust;

using Xunit;

namespace Kiota.Builder.Tests.Writers.Rust;

public sealed class CodeClassDeclarationWriterTests : IDisposable
{
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private const string DefaultNameSpace = "ns";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeClassDeclarationWriter codeElementWriter;
    private readonly CodeClass parentClass;
    private readonly CodeNamespace root;

    public CodeClassDeclarationWriterTests()
    {
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.Rust, DefaultPath, DefaultName);
        codeElementWriter = new CodeClassDeclarationWriter(new RustConventionService(), DefaultNameSpace, (Builder.PathSegmenters.RustPathSegmenter)writer.PathSegmenter);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        root = CodeNamespace.InitRootNamespace();
        parentClass = new()
        {
            Name = "parentClass"
        };
        root.AddClass(parentClass);
    }
    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }
    [Fact]
    public void WritesSimpleDeclaration()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("pub struct", result);
        Assert.Contains("ParentClass", result);
    }
    [Fact]
    public void WritesModelWithSerdeDerives()
    {
        parentClass.Kind = CodeClassKind.Model;
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("#[derive(Debug, Clone, Default, Serialize, Deserialize)]", result);
        Assert.Contains("pub struct", result);
    }
    [Fact]
    public void WritesRequestBuilderWithoutSerdeDerives()
    {
        parentClass.Kind = CodeClassKind.RequestBuilder;
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("#[derive(Debug, Clone)]", result);
        Assert.DoesNotContain("Serialize", result);
        Assert.DoesNotContain("Deserialize", result);
    }
    [Fact]
    public void WritesAutoGeneratedComment()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("// auto-generated by kiota", result);
    }
}
