// <auto-generated/>
using ApiSdk.Groups.Item.Artifacts;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Groups.Item {
    /// <summary>
    /// Builds and executes requests for operations under \groups\{groupId}
    /// </summary>
    public class WithGroupItemRequestBuilder : BaseRequestBuilder {
        /// <summary>The artifacts property</summary>
        public ArtifactsRequestBuilder Artifacts { get =>
            new ArtifactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new WithGroupItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGroupItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupId}", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new WithGroupItemRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGroupItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/groups/{groupId}", rawUrl) {
        }
    }
}
