/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kiota.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RequestInfoTest {
    @Test void testSomeLibraryMethod() {
        RequestInfoTest classUnderTest = new RequestInfoTest();
        assertNotNull(classUnderTest);
    }
}
