using System;
using System.IO;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;
using Kiota.Builder.Writers.CSharp;

using Xunit;

namespace Kiota.Builder.Tests.Writers.CSharp;

public sealed class CodeClassDeclarationWriterTests : IDisposable
{
    private const string AutoGenerationHeader = "// <auto-generated/>";
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeClassDeclarationWriter codeElementWriter;
    private readonly CodeClass parentClass;

    public CodeClassDeclarationWriterTests()
    {
        codeElementWriter = new CodeClassDeclarationWriter(new CSharpConventionService());
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.CSharp, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        var root = CodeNamespace.InitRootNamespace();
        parentClass = new()
        {
            Name = "parentClass"
        };
        root.AddClass(parentClass);
    }

    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public void WritesAutoGeneratedHeader()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains(AutoGenerationHeader, result);
    }

    [Fact]
    public void WritesSimpleDeclaration()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("public partial class", result);
    }

    [Fact]
    public void WritesWarningDisableCs0618()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("#pragma warning disable CS0618", result);
    }

    [Fact]
    public void WritesImplementation()
    {
        var declaration = parentClass.StartBlock;
        declaration.AddImplements(new CodeType
        {
            Name = "someInterface"
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.Contains(":", result);
    }

    [Fact]
    public void WritesInheritance()
    {
        var declaration = parentClass.StartBlock;
        declaration.Inherits = new()
        {
            Name = "someInterface"
        };
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.Contains(":", result);
    }

    [Fact]
    public void WritesImports()
    {
        var declaration = parentClass.StartBlock;
        declaration.AddUsings(new()
        {
            Name = "Objects",
            Declaration = new()
            {
                Name = "system.util",
                IsExternal = true,
            }
        },
        new()
        {
            Name = "project.graph",
            Declaration = new()
            {
                Name = "Message",
            }
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.Contains("using", result);
        Assert.Contains("Project.Graph", result);
        Assert.Contains("System.Util", result);
    }

    [Fact]
    public void WritesGeneratedCodeAttribute()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Matches(CodeEnumWriterTests.GeneratedCodePattern, result);
    }

    [Theory]
    [InlineData(AccessModifier.Public)]
    [InlineData(AccessModifier.Internal)]
    public void WritesAccessModifier(AccessModifier accessModifier)
    {
        parentClass.Access = accessModifier;
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains($"{accessModifier.ToString().ToLower()} partial class", result);
    }

    [Fact]
    public void WritesGenericDerivedConstructorForwardingToGenericBase()
    {
        var itemTypeParameter = new CodeTypeParameter { Name = "TItemType" };
        parentClass.StartBlock.AddTypeParameter(itemTypeParameter);
        var baseClass = new CodeClass { Name = "BasePage" };
        baseClass.StartBlock.AddTypeParameter(new CodeTypeParameter { Name = "TItemType" }); // the base owns its parameter instance
        var inherits = new CodeType { TypeDefinition = baseClass };
        inherits.AddGenericTypeParameterValue(new CodeType { TypeDefinition = parentClass.TypeParameters[0] }); // derived closes over its own parameter
        parentClass.StartBlock.Inherits = inherits;
        parentClass.AddProperty(new CodeProperty
        {
            Name = "page",
            Type = new CodeType { Name = "int", IsExternal = true },
        });
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("public ParentClass(ParsableFactory<TItemType> itemTypeFactory) : base(itemTypeFactory)", result);
        // the derived class deserializes no TItemType property of its own, the base owns the factory field
        Assert.DoesNotContain("_itemTypeFactory", result);
    }

    [Fact]
    public void WritesFactoryFieldOnlyForOwnDeserializers()
    {
        var itemTypeParameter = new CodeTypeParameter { Name = "TItemType" };
        parentClass.StartBlock.AddTypeParameter(itemTypeParameter);
        var itemsType = new CodeType { TypeDefinition = itemTypeParameter, CollectionKind = CodeTypeBase.CodeTypeCollectionKind.Complex };
        parentClass.AddProperty(new CodeProperty
        {
            Name = "items",
            Type = itemsType,
        });
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("private readonly ParsableFactory<TItemType> _itemTypeFactory;", result);
        Assert.Contains("_itemTypeFactory = itemTypeFactory;", result);
    }
}
