using System;
using Kiota.Builder.CodeDOM;
namespace Kiota.Builder.Writers.TypeScript;

public class CodeFileBlockEndWriter : BaseElementWriter<CodeFileBlockEnd, TypeScriptConventionService>
{
    public CodeFileBlockEndWriter(TypeScriptConventionService conventionService) : base(conventionService)
    {
    }

    public override void WriteCodeElement(CodeFileBlockEnd codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);
        conventions.WriteAutoGeneratedEnd(writer);
    }
}
