using System;
using System.Linq;
using Kiota.Builder.CodeDOM;

namespace Kiota.Builder.Writers.TypeScript;

public class CodeFileDeclarationWriter : BaseElementWriter<CodeFileDeclaration, TypeScriptConventionService>
{
    private readonly CodeUsingWriter _codeUsingWriter;
    public CodeFileDeclarationWriter(TypeScriptConventionService conventionService, string clientNamespaceName) : base(conventionService)
    {
        _codeUsingWriter = new(clientNamespaceName);
    }

    public override void WriteCodeElement(CodeFileDeclaration codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        if (codeElement.Parent is CodeFile cf && cf.Parent is CodeNamespace ns)
        {
            var usings = cf.GetChildElements().SelectMany(static x =>
                {
                    return x switch
                    {
                        CodeFunction f => f.StartBlock.Usings,
                        CodeInterface ci => ci.Usings,
                        CodeClass cc => cc.Usings,
                        _ => Enumerable.Empty<CodeUsing>()
                    };
                }
            );
            conventions.WriteAutoGeneratedStart(writer);

            // remove duplicate using, keep a single using for each internal type in the same namespace
            var enumeratedUsing = usings.ToArray();
            var filteredUsing = enumeratedUsing.Where(x => x.IsExternal)
                .Union(enumeratedUsing.ToArray()
                    .Where(x => x is { IsExternal: false, Declaration.TypeDefinition: not null })
                    .GroupBy(x =>
                        $"{x.Declaration!.TypeDefinition!.GetImmediateParentOfType<CodeNamespace>().Name}.{x.Declaration?.Name.ToLowerInvariant()}")
                    .Select(x => x.First()));

            _codeUsingWriter.WriteCodeElement(filteredUsing, ns, writer);
        }
    }

}
