using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

using static Kiota.Builder.CodeDOM.CodeTypeBase;

namespace Kiota.Builder.Writers.TypeScript;
public class TypeScriptConventionService : CommonLanguageConventionService
{
    internal void WriteAutoGeneratedStart(LanguageWriter writer)
    {
        writer.WriteLine("/* tslint:disable */");
        writer.WriteLine("/* eslint-disable */");
        writer.WriteLine("// Generated by Microsoft Kiota");
    }
    internal void WriteAutoGeneratedEnd(LanguageWriter writer)
    {
        writer.WriteLine("/* tslint:enable */");
        writer.WriteLine("/* eslint-enable */");
    }
    public override string StreamTypeName => "ArrayBuffer";
    public override string VoidTypeName => "void";
    public override string DocCommentPrefix => " * ";
    public override string ParseNodeInterfaceName => "ParseNode";
    internal string DocCommentStart = "/**";
    internal string DocCommentEnd = " */";
    public override string TempDictionaryVarName => "urlTplParams";
    internal void AddParametersAssignment(LanguageWriter writer, CodeTypeBase pathParametersType, string pathParametersReference, string varName = "", params (CodeTypeBase, string, string)[] parameters)
    {
        if (pathParametersType == null) return;
        if (string.IsNullOrEmpty(varName))
        {
            varName = TempDictionaryVarName;
            writer.WriteLine($"const {varName} = getPathParameters({pathParametersReference});");
        }
        if (parameters.Length != 0)
            writer.WriteLines(parameters.Select(p =>
                $"{varName}[\"{p.Item2}\"] = {p.Item3}"
            ).ToArray());
    }
    public override string GetAccessModifier(AccessModifier access)
    {
        return access switch
        {
            AccessModifier.Public => "public",
            AccessModifier.Protected => "protected",
            _ => "private",
        };
    }

    public override string GetParameterSignature(CodeParameter parameter, CodeElement targetElement, LanguageWriter? writer = null)
    {
        ArgumentNullException.ThrowIfNull(parameter);
        var paramType = GetTypeString(parameter.Type, targetElement);
        var defaultValueSuffix = (string.IsNullOrEmpty(parameter.DefaultValue), parameter.Kind) switch
        {
            (false, CodeParameterKind.DeserializationTarget) => $" = {parameter.DefaultValue}",
            (false, _) => $" = {parameter.DefaultValue} as {paramType}",
            (true, _) => string.Empty,
        };
        var (partialPrefix, partialSuffix) = parameter.Kind switch
        {
            CodeParameterKind.DeserializationTarget => ("Partial<", ">"),
            _ => (string.Empty, string.Empty),
        };
        return $"{parameter.Name.ToFirstCharacterLowerCase()}{(parameter.Optional && parameter.Type.IsNullable ? "?" : string.Empty)}: {partialPrefix}{paramType}{partialSuffix}{(parameter.Type.IsNullable ? " | undefined" : string.Empty)}{defaultValueSuffix}";
    }
    public override string GetTypeString(CodeTypeBase code, CodeElement targetElement, bool includeCollectionInformation = true, LanguageWriter? writer = null)
    {
        ArgumentNullException.ThrowIfNull(code);
        ArgumentNullException.ThrowIfNull(targetElement);
        var collectionSuffix = code.CollectionKind == CodeTypeCollectionKind.None || !includeCollectionInformation ? string.Empty : "[]";
        if (code is CodeComposedTypeBase currentUnion && currentUnion.Types.Any())
            return string.Join(" | ", currentUnion.Types.Select(x => GetTypeString(x, targetElement))) + collectionSuffix;
        if (code is CodeType currentType)
        {
            var typeName = GetTypeAlias(currentType, targetElement) is string alias && !string.IsNullOrEmpty(alias) ? alias : TranslateType(currentType);
            var genericParameters = currentType.GenericTypeParameterValues.Any() ?
                $"<{string.Join(", ", currentType.GenericTypeParameterValues.Select(x => GetTypeString(x, targetElement, includeCollectionInformation)))}>" :
                string.Empty;
            return $"{typeName}{collectionSuffix}{genericParameters}";
        }

        throw new InvalidOperationException($"type of type {code.GetType()} is unknown");
    }
    private static string GetTypeAlias(CodeType targetType, CodeElement targetElement)
    {
        if (targetElement.GetImmediateParentOfType<IBlock>() is IBlock parentBlock &&
            parentBlock.Usings
                        .FirstOrDefault(x => !x.IsExternal &&
                                        x.Declaration?.TypeDefinition != null &&
                                        x.Declaration.TypeDefinition == targetType.TypeDefinition &&
                                        !string.IsNullOrEmpty(x.Alias)) is CodeUsing aliasedUsing)
            return aliasedUsing.Alias;
        return string.Empty;
    }

    public override string TranslateType(CodeType type)
    {
        return type?.Name switch
        {
            "integer" or "int64" or "float" or "double" or "byte" or "sbyte" or "decimal" => "number",
            "binary" or "base64" or "base64url" => "string",
            "Guid" => "Guid",
            "String" or "Object" or "Boolean" or "Void" or "string" or "object" or "boolean" or "void" => type.Name.ToFirstCharacterLowerCase(), // little casing hack
            null => "object",
            _ => GetCodeTypeName(type) is string typeName && !string.IsNullOrEmpty(typeName) ? typeName : "object",
        };
    }

    private static string GetCodeTypeName(CodeType codeType)
    {
        if (codeType.TypeDefinition is CodeFunction codeFunction)
        {
            return !string.IsNullOrEmpty(codeFunction.Name) ? codeFunction.Name : string.Empty;
        }

        return (!string.IsNullOrEmpty(codeType.TypeDefinition?.Name) ? codeType.TypeDefinition.Name : codeType.Name).ToFirstCharacterUpperCase();
    }
#pragma warning disable CA1822 // Method should be static
    public bool IsPrimitiveType(string typeName)
    {
        return typeName switch
        {
            "number" or "string" or "byte[]" or "boolean" or "void" => true,
            _ => false,
        };
    }
#pragma warning restore CA1822 // Method should be static
    internal static string RemoveInvalidDescriptionCharacters(string originalDescription) => originalDescription?.Replace("\\", "/", StringComparison.OrdinalIgnoreCase) ?? string.Empty;
    public override bool WriteShortDescription(IDocumentedElement element, LanguageWriter writer, string prefix = "", string suffix = "")
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(element);
        if (!element.Documentation.DescriptionAvailable) return false;
        if (element is not CodeElement codeElement) return false;

        var description = element.Documentation.GetDescription(type => GetTypeString(type, codeElement), ReferenceTypePrefix, ReferenceTypeSuffix, RemoveInvalidDescriptionCharacters);
        writer.WriteLine($"{DocCommentStart} {description}{DocCommentEnd}");

        return true;
    }
    internal const string ReferenceTypePrefix = "{@link ";
    internal const string ReferenceTypeSuffix = "}";
    public void WriteLongDescription(IDocumentedElement documentedElement, LanguageWriter writer, IEnumerable<string>? additionalRemarks = default)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(documentedElement);
        if (documentedElement.Documentation is null) return;
        if (documentedElement is not CodeElement codeElement) return;
        additionalRemarks ??= [];
        var remarks = additionalRemarks.Where(static x => !string.IsNullOrEmpty(x)).ToArray();
        if (documentedElement.Documentation.DescriptionAvailable || documentedElement.Documentation.ExternalDocumentationAvailable || remarks.Length != 0)
        {
            writer.WriteLine(DocCommentStart);
            if (documentedElement.Documentation.DescriptionAvailable)
            {
                var description = documentedElement.Documentation.GetDescription(type => GetTypeString(type, codeElement), ReferenceTypePrefix, ReferenceTypeSuffix, RemoveInvalidDescriptionCharacters);
                writer.WriteLine($"{DocCommentPrefix}{description}");
            }
            foreach (var additionalRemark in remarks)
                writer.WriteLine($"{DocCommentPrefix}{additionalRemark}");

            if (documentedElement is IDeprecableElement deprecableElement && GetDeprecationComment(deprecableElement) is string deprecationComment && !string.IsNullOrEmpty(deprecationComment))
                writer.WriteLine($"{DocCommentPrefix}{deprecationComment}");

            if (documentedElement.Documentation.ExternalDocumentationAvailable)
                writer.WriteLine($"{DocCommentPrefix}@see {{@link {documentedElement.Documentation.DocumentationLink}|{documentedElement.Documentation.DocumentationLabel}}}");
            writer.WriteLine(DocCommentEnd);
        }
    }
    private string GetDeprecationComment(IDeprecableElement element)
    {
        if (element.Deprecation is null || !element.Deprecation.IsDeprecated) return string.Empty;

        var versionComment = string.IsNullOrEmpty(element.Deprecation.Version) ? string.Empty : $" as of {element.Deprecation.Version}";
        var dateComment = element.Deprecation.Date is null ? string.Empty : $" on {element.Deprecation.Date.Value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}";
        var removalComment = element.Deprecation.RemovalDate is null ? string.Empty : $" and will be removed {element.Deprecation.RemovalDate.Value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}";
        return $"@deprecated {element.Deprecation.GetDescription(type => GetTypeString(type, (element as CodeElement)!))}{versionComment}{dateComment}{removalComment}";
    }
}
