# frozen_string_literal: true

require_relative 'microsoft_kiota_nethttplibrary/version'
require_relative 'microsoft_kiota_nethttplibrary/net_http_request_adapter'

module MicrosoftKiotaNethttplibrary
end
