sonar.organization=microsoft
// x-release-please-start-version
sonar.projectVersion=10.4.1
// x-release-please-end
sonar.host.url=https://sonarcloud.io


sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.ts
sonar.exclusions=node_modules, dist
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage\cobertura-coverage.xml,
