name: Kiota Feature request
description: Request a new feature on Kiota
labels: ["type:feature", "status:waiting-for-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this feature request form!**
        💥Please search to see if an issue already exists for the feature you are requesting.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe the problem.
      description: A clear and concise description of what the problem is.
      placeholder: I am trying to do [...] but [...]
    validations:
      required: false
  - type: dropdown
    id: language
    attributes:
      label: Client library/SDK language
      description: Is feature request related to any client library/SDK language?
      multiple: false
      options:
        - Csharp
        - CLI
        - Go
        - Java
        - PHP
        - PowerShell
        - Python
        - Ruby
        - TypeScript
        - Swift
        - Dart
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
