using System;
using System.Collections.Generic;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.Rust;

public class CodeClassDeclarationWriter(RustConventionService conventionService) : BaseElementWriter<ClassDeclaration, RustConventionService>(conventionService)
{
    public override void WriteCodeElement(ClassDeclaration codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        if (codeElement.Parent is not CodeClass parentClass)
            throw new InvalidOperationException("ClassDeclaration parent is not a CodeClass");

        // nested classes: config/query params remain after composed types were promoted
        if (parentClass.Parent is CodeClass)
        {
            if (parentClass.IsOfKind(CodeClassKind.QueryParameters))
            {
                WriteQueryParametersClass(parentClass, writer);
                return;
            }
            // skip config classes and others
            return;
        }

        var className = parentClass.Name.ToFirstCharacterUpperCase();
        var isModel = parentClass.IsOfKind(CodeClassKind.Model);
        var isRequestBuilder = parentClass.IsOfKind(CodeClassKind.RequestBuilder);
        var hasBase = isRequestBuilder && codeElement.Inherits?.AllTypes?.Any() == true;

        // figure out the root client namespace so we can strip it from import paths
        if (_clientNamespace == null)
        {
            var ns = parentClass.Parent as CodeNamespace;
            while (ns?.Parent is CodeNamespace parent && !string.IsNullOrEmpty(parent.Name))
                ns = parent;
            _clientNamespace = ns?.Name ?? string.Empty;
        }

        // file header + imports
        writer.WriteLine("// Code generated by Microsoft Kiota - DO NOT EDIT.");
        writer.WriteLine();
        WriteImports(parentClass, isModel, isRequestBuilder, writer);

        // struct definition
        conventions.WriteShortDescription(parentClass, writer);
        writer.WriteLine("#[derive(Debug, Clone, Default, PartialEq)]");
        writer.WriteLine($"pub struct {className} {{");
        writer.IncreaseIndent();

        if (hasBase)
            writer.WriteLine("pub base: BaseRequestBuilder,");

        foreach (var prop in parentClass.Properties
            .Where(p => p.Kind is not (CodePropertyKind.RequestBuilder or CodePropertyKind.AdditionalData))
            .Where(p => !hasBase || !IsBaseProperty(p))
            .OrderBy(static p => p.Name, StringComparer.OrdinalIgnoreCase))
        {
            var propType = conventions.GetTypeString(prop.Type, prop);
            var propName = prop.Name.ToSnakeCase();
            conventions.WriteShortDescription(prop, writer);
            writer.WriteLine($"pub {propName}: {propType},");
        }

        // additional data uses a fixed type
        if (parentClass.GetPropertyOfKind(CodePropertyKind.AdditionalData) is not null)
            writer.WriteLine("pub additional_data: HashMap<String, serde_json::Value>,");

        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // Parsable trait impl for model classes
        if (isModel)
            WriteParsableImpl(parentClass, className, writer);

        // regular impl block for methods
        writer.WriteLine($"impl {className} {{");
        writer.IncreaseIndent();
    }

    private void WriteParsableImpl(CodeClass parentClass, string className, LanguageWriter writer)
    {
        var customProps = parentClass.GetPropertiesOfKind(CodePropertyKind.Custom)
            .OrderBy(static p => p.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        writer.WriteLine($"impl Parsable for {className} {{");
        writer.IncreaseIndent();

        // field_names
        writer.WriteLine("fn field_names(&self) -> Vec<&'static str> {");
        writer.IncreaseIndent();
        var names = string.Join(", ", customProps.Select(p =>
        {
            var wn = p.WireName;
            return $"\"{(string.IsNullOrEmpty(wn) ? p.Name : wn)}\"";
        }));
        writer.WriteLine($"vec![{names}]");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // assign_field
        writer.WriteLine("fn assign_field(&mut self, field: &str, node: &dyn ParseNode) -> Result<(), KiotaError> {");
        writer.IncreaseIndent();
        writer.WriteLine("match field {");
        writer.IncreaseIndent();
        foreach (var prop in customProps)
        {
            var wireName = prop.WireName;
            if (string.IsNullOrEmpty(wireName))
                wireName = prop.Name;
            var propName = prop.Name.ToSnakeCase();

            var isCollection = prop.Type.CollectionKind != CodeTypeBase.CodeTypeCollectionKind.None;

            if (isCollection)
            {
                var innerType = prop.Type is CodeType collType ? collType : null;
                var innerTypeDef = innerType?.TypeDefinition;
                if (innerTypeDef is CodeClass innerClass)
                {
                    // collection of objects
                    var innerTypeName = innerClass.Name.ToFirstCharacterUpperCase();
                    writer.WriteLine($"\"{wireName}\" => {{");
                    writer.IncreaseIndent();
                    writer.WriteLine($"let mut items = Vec::new();");
                    writer.WriteLine($"for child in node.get_child_nodes()? {{");
                    writer.IncreaseIndent();
                    writer.WriteLine($"let mut obj = {innerTypeName}::default();");
                    writer.WriteLine($"for f in obj.field_names().to_vec() {{");
                    writer.IncreaseIndent();
                    writer.WriteLine($"if let Ok(Some(n)) = child.get_child_node(f) {{ obj.assign_field(f, n.as_ref())?; }}");
                    writer.DecreaseIndent();
                    writer.WriteLine($"}}");
                    writer.WriteLine($"items.push(obj);");
                    writer.DecreaseIndent();
                    writer.WriteLine($"}}");
                    writer.WriteLine($"self.{propName} = items;");
                    writer.DecreaseIndent();
                    writer.WriteLine($"}}");
                }
                else
                {
                    // collection of primitives (strings, ints, etc.)
                    writer.WriteLine($"\"{wireName}\" => self.{propName} = node.get_collection_of_string_values()?,");
                }
            }
            else if (prop.Type is CodeType ct && ct.TypeDefinition is CodeEnum enumDef)
            {
                var enumType = enumDef.Name.ToFirstCharacterUpperCase();
                writer.WriteLine($"\"{wireName}\" => self.{propName} = node.get_string_value()?.and_then(|s| {enumType}::parse(&s)),");
            }
            else if (prop.Type is CodeType ct2 && ct2.TypeDefinition is CodeClass objClass)
            {
                // nested object
                var objTypeName = objClass.Name.ToFirstCharacterUpperCase();
                writer.WriteLine($"\"{wireName}\" => {{");
                writer.IncreaseIndent();
                writer.WriteLine($"let mut obj = {objTypeName}::default();");
                writer.WriteLine($"for f in obj.field_names().to_vec() {{");
                writer.IncreaseIndent();
                writer.WriteLine($"if let Ok(Some(n)) = node.get_child_node(f) {{ obj.assign_field(f, n.as_ref())?; }}");
                writer.DecreaseIndent();
                writer.WriteLine($"}}");
                writer.WriteLine($"self.{propName} = Some(obj);");
                writer.DecreaseIndent();
                writer.WriteLine($"}}");
            }
            else
            {
                var rawType = prop.Type is CodeType ct3 ? conventions.TranslateType(ct3) : "String";
                var readMethod = GetReadMethodForType(rawType);
                writer.WriteLine($"\"{wireName}\" => self.{propName} = node.{readMethod}()?,");
            }
        }
        writer.WriteLine("_ => {}");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine("Ok(())");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // serialize
        writer.WriteLine("fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), KiotaError> {");
        writer.IncreaseIndent();
        foreach (var prop in customProps)
        {
            var wireName = prop.WireName;
            if (string.IsNullOrEmpty(wireName))
                wireName = prop.Name;
            var propName = prop.Name.ToSnakeCase();
            var rawType = prop.Type is CodeType ct ? conventions.TranslateType(ct) : "String";
            var isEnum = prop.Type is CodeType ct2 && ct2.TypeDefinition is CodeEnum;
            var writeMethod = GetWriteMethodForType(rawType);
            var needsRef = rawType == "String" || rawType.StartsWith("chrono::", StringComparison.Ordinal)
                || rawType.StartsWith("uuid::", StringComparison.Ordinal) || rawType == "IsoDuration";

            var isCollection = prop.Type.CollectionKind != CodeTypeBase.CodeTypeCollectionKind.None;

            if (isCollection)
            {
                // collection fields are never Option, they default to empty vec
                if (RustConventionService.IsPrimitiveType(rawType))
                    writer.WriteLine($"writer.write_collection_of_string_values(Some(\"{wireName}\"), &self.{propName}.iter().map(|v| v.to_string()).collect::<Vec<_>>())?;");
                else
                    writer.WriteLine($"// TODO: serialize collection of objects for {propName}");
            }
            else if (isEnum)
            {
                // enums implement Display, serialize as string
                if (prop.Type.IsNullable)
                    writer.WriteLine($"if let Some(ref val) = self.{propName} {{ writer.write_string_value(Some(\"{wireName}\"), &val.to_string())?; }}");
                else
                    writer.WriteLine($"writer.write_string_value(Some(\"{wireName}\"), &self.{propName}.to_string())?;");
            }
            else if (prop.Type.IsNullable && RustConventionService.IsPrimitiveType(rawType))
            {
                if (needsRef)
                    writer.WriteLine($"if let Some(ref val) = self.{propName} {{ writer.{writeMethod}(Some(\"{wireName}\"), val)?; }}");
                else
                    writer.WriteLine($"if let Some(val) = self.{propName} {{ writer.{writeMethod}(Some(\"{wireName}\"), val)?; }}");
            }
            else if (RustConventionService.IsPrimitiveType(rawType))
            {
                writer.WriteLine($"writer.{writeMethod}(Some(\"{wireName}\"), self.{propName}.clone())?;");
            }
            else if (prop.Type.IsNullable)
            {
                writer.WriteLine($"if let Some(ref val) = self.{propName} {{ writer.write_object_value(Some(\"{wireName}\"), val as &dyn Parsable, &[])?; }}");
            }
            else
            {
                writer.WriteLine($"writer.write_object_value(Some(\"{wireName}\"), &self.{propName} as &dyn Parsable, &[])?;");
            }
        }

        if (parentClass.GetPropertyOfKind(CodePropertyKind.AdditionalData) is not null)
            writer.WriteLine("writer.write_additional_data(&self.additional_data)?;");

        writer.WriteLine("Ok(())");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // as_any for downcasting
        writer.WriteLine("fn as_any(self: Box<Self>) -> Box<dyn std::any::Any> {");
        writer.IncreaseIndent();
        writer.WriteLine("self");
        writer.DecreaseIndent();
        writer.WriteLine("}");

        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static string GetReadMethodForType(string typeName)
    {
        return typeName switch
        {
            "String" => "get_string_value",
            "bool" => "get_bool_value",
            "i32" => "get_i32_value",
            "i64" => "get_i64_value",
            "f32" => "get_f32_value",
            "f64" => "get_f64_value",
            "u8" => "get_u8_value",
            "i8" => "get_i8_value",
            "uuid::Uuid" => "get_uuid_value",
            "Vec<u8>" => "get_byte_array_value",
            "chrono::DateTime<chrono::FixedOffset>" => "get_date_time_value",
            "chrono::NaiveDate" => "get_date_only_value",
            "chrono::NaiveTime" => "get_time_only_value",
            "IsoDuration" => "get_duration_value",
            _ => "get_string_value",
        };
    }

    private static string GetWriteMethodForType(string typeName)
    {
        return typeName switch
        {
            "String" => "write_string_value",
            "bool" => "write_bool_value",
            "i32" => "write_i32_value",
            "i64" => "write_i64_value",
            "f32" => "write_f32_value",
            "f64" => "write_f64_value",
            "u8" => "write_u8_value",
            "i8" => "write_i8_value",
            "uuid::Uuid" => "write_uuid_value",
            "Vec<u8>" => "write_byte_array_value",
            "chrono::DateTime<chrono::FixedOffset>" => "write_date_time_value",
            "chrono::NaiveDate" => "write_date_only_value",
            "chrono::NaiveTime" => "write_time_only_value",
            "IsoDuration" => "write_duration_value",
            _ => "write_string_value",
        };
    }

    private static void WriteImports(CodeClass parentClass, bool isModel, bool isRequestBuilder, LanguageWriter writer)
    {
        var hasAdditionalData = parentClass.GetPropertyOfKind(CodePropertyKind.AdditionalData) is not null;
        var hasExecutors = parentClass.Methods.Any(m => m.IsOfKind(CodeMethodKind.RequestExecutor));
        var hasConstructors = parentClass.Methods.Any(m => m.IsOfKind(
            CodeMethodKind.Constructor, CodeMethodKind.ClientConstructor, CodeMethodKind.RawUrlConstructor));
        var hasGenerators = parentClass.Methods.Any(m => m.IsOfKind(CodeMethodKind.RequestGenerator));

        if (isModel && hasAdditionalData)
            writer.WriteLine("use std::collections::HashMap;");
        if (isRequestBuilder)
        {
            var abstractions = new List<string> { "BaseRequestBuilder" };
            if (hasConstructors)
                abstractions.Add("RequestAdapter");
            if (hasExecutors)
            {
                abstractions.Add("KiotaError");
                abstractions.Add("Parsable");
                abstractions.Add("ParseNode");
            }
            if (hasGenerators)
            {
                abstractions.Add("DefaultQueryParameters");
                abstractions.Add("HttpMethod");
                abstractions.Add("KiotaError");
                abstractions.Add("RequestConfiguration");
                abstractions.Add("RequestInformation");
            }
            // check if any method param is MultipartBody
            if (parentClass.Methods.Any(m => m.Parameters.Any(p =>
                p.Type.Name.Equals("MultipartBody", StringComparison.OrdinalIgnoreCase))))
                abstractions.Add("MultipartBody");
            abstractions = abstractions.Distinct().OrderBy(static x => x, StringComparer.Ordinal).ToList();
            writer.WriteLine($"use kiota_abstractions::{{{string.Join(", ", abstractions)}}};");
        }
        if (isModel)
        {
            writer.WriteLine("use kiota_abstractions::{KiotaError, Parsable, ParseNode, SerializationWriter};");
        }

        // external crate imports based on field types
        var allTypes = parentClass.Properties
            .Where(static p => p.Type is CodeType)
            .Select(static p => ((CodeType)p.Type).Name.ToLowerInvariant())
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        if (allTypes.Any(t => t.Contains("datetime", StringComparison.OrdinalIgnoreCase) || t.Contains("dateonly", StringComparison.OrdinalIgnoreCase) || t.Contains("timeonly", StringComparison.OrdinalIgnoreCase)))
            writer.WriteLine("use chrono;");
        if (allTypes.Contains("guid") || allTypes.Contains("uuid"))
            writer.WriteLine("use uuid;");

        // collect external type references from methods/properties, excluding self
        var referencedTypes = new HashSet<string>(StringComparer.Ordinal);
        var selfName = parentClass.Name;
        foreach (var method in parentClass.Methods)
        {
            CollectTypeRef(method.ReturnType, referencedTypes, selfName);
            foreach (var param in method.Parameters)
                CollectTypeRef(param.Type, referencedTypes, selfName);
        }
        foreach (var prop in parentClass.Properties)
            CollectTypeRef(prop.Type, referencedTypes, selfName);

        foreach (var import in referencedTypes.OrderBy(static x => x, StringComparer.Ordinal))
            writer.WriteLine($"use crate::{import};");

        writer.WriteLine();
    }

    private static readonly HashSet<string> BuiltinTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "String", "bool", "i8", "u8", "i32", "i64", "f32", "f64",
        "void", "Vec", "Option", "HashMap", "serde_json",
        "BaseRequestBuilder", "RequestAdapter", "RequestInformation",
        "RequestConfiguration", "DefaultQueryParameters", "HttpMethod",
        "KiotaError", "Parsable", "ParseNode", "SerializationWriter",
        "MultipartBody",
    };

    private static string? _clientNamespace;

    private static void CollectTypeRef(CodeTypeBase typeBase, HashSet<string> refs, string selfName)
    {
        if (typeBase is not CodeType ct) return;
        if (BuiltinTypes.Contains(ct.Name)) return;

        // handle both CodeClass and CodeEnum references
        CodeElement? refElement = ct.TypeDefinition;
        if (refElement is not (CodeClass or CodeEnum)) return;
        if (refElement.Name.Equals(selfName, StringComparison.OrdinalIgnoreCase)) return;

        // find the containing namespace — use GetImmediateParentOfType to handle
        // both direct namespace children and classes nested inside other classes
        var ns = refElement.GetImmediateParentOfType<CodeNamespace>()?.Name ?? string.Empty;
        if (_clientNamespace != null && ns.StartsWith(_clientNamespace, StringComparison.Ordinal))
        {
            ns = ns.Length > _clientNamespace.Length
                ? ns[(_clientNamespace.Length + 1)..]
                : string.Empty;
        }

        var parts = ns.Split('.', StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.ToSnakeCase()).ToList();
        var typeName = refElement.Name.ToSnakeCase();
        parts.Add(typeName);
        parts.Add(refElement.Name.ToFirstCharacterUpperCase());
        var path = string.Join("::", parts);
        if (!string.IsNullOrEmpty(path))
            refs.Add(path);
    }

    private void WriteQueryParametersClass(CodeClass parentClass, LanguageWriter writer)
    {
        // close the parent request builder's impl block
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        var qpName = parentClass.Name.ToFirstCharacterUpperCase();
        var props = parentClass.Properties
            .OrderBy(static p => p.Name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        // struct
        writer.WriteLine($"#[derive(Debug, Clone, Default)]");
        writer.WriteLine($"pub struct {qpName} {{");
        writer.IncreaseIndent();
        foreach (var prop in props)
        {
            conventions.WriteShortDescription(prop, writer);
            var propName = prop.Name.ToSnakeCase();
            // query params are always strings or collections of strings
            var isCollection = prop.Type.CollectionKind != CodeTypeBase.CodeTypeCollectionKind.None;
            string propType;
            if (isCollection)
                propType = "Vec<String>";
            else if (prop.Type.IsNullable)
                propType = "Option<String>";
            else
                propType = "String";
            writer.WriteLine($"pub {propName}: {propType},");
        }
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // QueryParameters trait impl
        writer.WriteLine($"impl kiota_abstractions::QueryParameters for {qpName} {{");
        writer.IncreaseIndent();
        writer.WriteLine("fn to_query_parameters(&self) -> std::collections::HashMap<String, String> {");
        writer.IncreaseIndent();
        writer.WriteLine("let mut params = std::collections::HashMap::new();");
        foreach (var prop in props)
        {
            var propName = prop.Name.ToSnakeCase();
            var wireName = !string.IsNullOrEmpty(prop.WireName) ? prop.WireName
                : !string.IsNullOrEmpty(prop.SerializationName) ? prop.SerializationName
                : prop.Name;
            var rawType = prop.Type is CodeType ct ? conventions.TranslateType(ct) : "String";

            var isCollection = prop.Type.CollectionKind != CodeTypeBase.CodeTypeCollectionKind.None;
            if (isCollection)
            {
                writer.WriteLine($"if !self.{propName}.is_empty() {{ params.insert(\"{wireName}\".to_string(), self.{propName}.join(\",\")); }}");
            }
            else if (prop.Type.IsNullable)
            {
                writer.WriteLine($"if let Some(ref v) = self.{propName} {{ params.insert(\"{wireName}\".to_string(), v.to_string()); }}");
            }
            else
            {
                writer.WriteLine($"params.insert(\"{wireName}\".to_string(), self.{propName}.to_string());");
            }
        }
        writer.WriteLine("params");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.DecreaseIndent();
        writer.WriteLine("}");
    }

    private static bool IsBaseProperty(CodeProperty prop)
    {
        return prop.Kind is CodePropertyKind.PathParameters
            or CodePropertyKind.RequestAdapter
            or CodePropertyKind.UrlTemplate
            or CodePropertyKind.Headers
            or CodePropertyKind.Options;
    }
}
