using System;
using System.Collections.Generic;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.Rust;

public class CodeFileDeclarationWriter(RustConventionService conventionService) : BaseElementWriter<CodeFileDeclaration, RustConventionService>(conventionService)
{
    public override void WriteCodeElement(CodeFileDeclaration codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        writer.WriteLine("// Code generated by Microsoft Kiota - DO NOT EDIT.");
        writer.WriteLine("// Changes may cause incorrect behavior and will be lost if the code is regenerated.");
        writer.WriteLine();

        var externalUsings = codeElement.Usings
            .Where(static x => x.Declaration is { IsExternal: true })
            .Select(static x => x.Declaration!.Name)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static x => x, StringComparer.OrdinalIgnoreCase)
            .ToList();

        foreach (var u in externalUsings)
        {
            writer.WriteLine($"use {u};");
        }

        var internalUsings = codeElement.Usings
            .Where(static x => x.Declaration is { IsExternal: false })
            .Select(static x => x.Name)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static x => x, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (internalUsings.Count > 0 && externalUsings.Count > 0)
            writer.WriteLine();

        foreach (var u in internalUsings)
        {
            writer.WriteLine($"use crate::{u.ToSnakeCase()};");
        }

        if (externalUsings.Count > 0 || internalUsings.Count > 0)
            writer.WriteLine();
    }
}
