using System;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.Rust;

public class CodeEnumWriter : BaseElementWriter<CodeEnum, RustConventionService>
{
    public CodeEnumWriter(RustConventionService conventionService) : base(conventionService) { }

    public override void WriteCodeElement(CodeEnum codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);
        if (!codeElement.Options.Any())
            return;

        conventions.WriteAutogeneratedMessage(writer);
        writer.WriteLine("use serde::{Serialize, Deserialize};");
        writer.WriteLine();

        conventions.WriteShortDescription(codeElement, writer);
        conventions.WriteDeprecationAttribute(codeElement, writer);
        writer.WriteLine("#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]");
        writer.StartBlock($"pub enum {codeElement.Name} {{");

        foreach (var option in codeElement.Options)
        {
            conventions.WriteShortDescription(option, writer);
            var serializationName = option.SerializationName;
            if (!string.IsNullOrEmpty(serializationName) && !serializationName.Equals(option.Name, StringComparison.Ordinal))
            {
                writer.WriteLine($"#[serde(rename = \"{serializationName}\")]");
            }
            writer.WriteLine($"{option.Name.ToFirstCharacterUpperCase()},");
        }
    }
}
