using System;
using System.Linq;
using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;
using Kiota.Builder.PathSegmenters;

namespace Kiota.Builder.Writers.Rust;

public class CodeClassDeclarationWriter : BaseElementWriter<ClassDeclaration, RustConventionService>
{
    private readonly RelativeImportManager relativeImportManager;

    public CodeClassDeclarationWriter(RustConventionService conventionService, string clientNamespaceName, RustPathSegmenter pathSegmenter) : base(conventionService)
    {
        ArgumentNullException.ThrowIfNull(pathSegmenter);
        relativeImportManager = new RelativeImportManager(clientNamespaceName, '.', (ns, element) => pathSegmenter.NormalizeFileName(element));
    }

    public override void WriteCodeElement(ClassDeclaration codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        if (codeElement.Parent is not CodeClass parentClass)
            throw new InvalidOperationException($"The provided code element {codeElement.Name} doesn't have a parent of type {nameof(CodeClass)}");

        conventions.WriteAutogeneratedMessage(writer);
        writer.WriteLine();

        // Write use statements for external dependencies
        if (codeElement.Parent?.Parent is CodeNamespace)
        {
            foreach (var externalUsing in codeElement.Usings
                    .Where(static x => x.IsExternal)
                    .DistinctBy(static x => x.Declaration!.Name, StringComparer.Ordinal)
                    .OrderBy(static x => x.Declaration!.Name, StringComparer.Ordinal))
            {
                writer.WriteLine($"use {externalUsing.Declaration!.Name};");
            }

            foreach (var internalUsing in codeElement.Usings
                    .Where(static x => !x.IsExternal)
                    .DistinctBy(static x => $"{x.Name}{x.Declaration?.Name}", StringComparer.OrdinalIgnoreCase)
                    .OrderBy(static x => x.Declaration?.Name, StringComparer.Ordinal))
            {
                var typeName = internalUsing.Declaration?.Name?.ToFirstCharacterUpperCase() ?? internalUsing.Name.ToFirstCharacterUpperCase();
                var modulePath = internalUsing.Declaration?.Name?.ToSnakeCase() ?? internalUsing.Name.ToSnakeCase();
                writer.WriteLine($"use crate::{modulePath};");
            }

            writer.WriteLine();
        }

        conventions.WriteLongDescription(parentClass, writer);
        conventions.WriteDeprecationAttribute(parentClass, writer);

        var isModel = parentClass.IsOfKind(CodeClassKind.Model);
        var isRequestBuilder = parentClass.IsOfKind(CodeClassKind.RequestBuilder);

        if (isModel)
        {
            // Model classes get serde derives
            var derives = new[] { "Debug", "Clone", "Default", "Serialize", "Deserialize" };
            writer.WriteLine($"#[derive({string.Join(", ", derives)})]");
        }
        else
        {
            writer.WriteLine("#[derive(Debug, Clone)]");
        }

        var structName = codeElement.Name.ToFirstCharacterUpperCase();
        writer.StartBlock($"pub struct {structName} {{");
    }
}
