using System;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.Rust;

public class CodeNamespaceWriter(RustConventionService conventionService) : BaseElementWriter<CodeNamespace, RustConventionService>(conventionService)
{
    public override void WriteCodeElement(CodeNamespace codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        writer.WriteLine("// Code generated by Microsoft Kiota - DO NOT EDIT.");
        writer.WriteLine();

        // Declare child namespaces as submodules
        foreach (var childNs in codeElement.GetChildElements(true).OfType<CodeNamespace>().OrderBy(static x => x.Name, StringComparer.OrdinalIgnoreCase))
        {
            var segmentName = childNs.Name.Split('.')[^1].ToSnakeCase();
            writer.WriteLine($"pub mod {segmentName};");
        }

        // Declare child classes/enums as submodules and re-export
        foreach (var childEnum in codeElement.GetChildElements(true).OfType<CodeEnum>().OrderBy(static x => x.Name, StringComparer.OrdinalIgnoreCase))
        {
            var modName = childEnum.Name.ToSnakeCase();
            writer.WriteLine($"pub mod {modName};");
        }

        foreach (var childClass in codeElement.GetChildElements(true).OfType<CodeClass>().OrderBy(static x => x.Name, StringComparer.OrdinalIgnoreCase))
        {
            var modName = childClass.Name.ToSnakeCase();
            writer.WriteLine($"pub mod {modName};");
        }

        foreach (var childFile in codeElement.GetChildElements(true).OfType<CodeFile>().OrderBy(static x => x.Name, StringComparer.OrdinalIgnoreCase))
        {
            var modName = childFile.Name.ToSnakeCase();
            writer.WriteLine($"pub mod {modName};");
        }
    }
}
