using System;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.Rust;

public class CodeEnumWriter(RustConventionService conventionService) : BaseElementWriter<CodeEnum, RustConventionService>(conventionService)
{
    public override void WriteCodeElement(CodeEnum codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        var enumName = codeElement.Name.ToFirstCharacterUpperCase();

        writer.WriteLine("// Code generated by Microsoft Kiota - DO NOT EDIT.");
        writer.WriteLine();

        conventions.WriteShortDescription(codeElement, writer);

        if (codeElement.Flags)
            writer.WriteLine("#[derive(Debug, Clone, PartialEq, Eq, Hash)]");
        else
            writer.WriteLine("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");

        writer.WriteLine($"pub enum {enumName} {{");
        writer.IncreaseIndent();
        foreach (var option in codeElement.Options)
        {
            conventions.WriteShortDescription(option, writer);
            writer.WriteLine($"{option.Name.ToFirstCharacterUpperCase()},");
        }
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // Display impl for serialization
        writer.WriteLine($"impl std::fmt::Display for {enumName} {{");
        writer.IncreaseIndent();
        writer.WriteLine("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
        writer.IncreaseIndent();
        writer.WriteLine("match self {");
        writer.IncreaseIndent();
        foreach (var option in codeElement.Options)
        {
            var wireName = option.WireName;
            if (string.IsNullOrEmpty(wireName))
                wireName = option.Name;
            writer.WriteLine($"Self::{option.Name.ToFirstCharacterUpperCase()} => write!(f, \"{wireName}\"),");
        }
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.WriteLine();

        // Parse function
        writer.WriteLine($"impl {enumName} {{");
        writer.IncreaseIndent();
        writer.WriteLine("pub fn parse(s: &str) -> Option<Self> {");
        writer.IncreaseIndent();
        writer.WriteLine("match s {");
        writer.IncreaseIndent();
        foreach (var option in codeElement.Options)
        {
            var wireName = option.WireName;
            if (string.IsNullOrEmpty(wireName))
                wireName = option.Name;
            writer.WriteLine($"\"{wireName}\" => Some(Self::{option.Name.ToFirstCharacterUpperCase()}),");
        }
        writer.WriteLine("_ => None,");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.DecreaseIndent();
        writer.WriteLine("}");
        writer.DecreaseIndent();
        writer.WriteLine("}");
    }
}
