using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

using static Kiota.Builder.CodeDOM.CodeTypeBase;

namespace Kiota.Builder.Writers.Rust;

public class RustConventionService : CommonLanguageConventionService
{
    internal static readonly HashSet<string> ErrorClassProperties = new(StringComparer.OrdinalIgnoreCase) { "message", "status_code", "response_headers" };
    public override string StreamTypeName => "Vec<u8>";
    public override string VoidTypeName => "()";
    public override string DocCommentPrefix => "/// ";
    internal const string NullableMarkerStr = "Option<";
    public override string ParseNodeInterfaceName => "ParseNode";
    private const string ReferenceTypePrefix = "[`";
    private const string ReferenceTypeSuffix = "`]";

    private static readonly HashSet<string> PrimitiveTypes = new(StringComparer.OrdinalIgnoreCase) {
        "i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64",
        "f32", "f64", "bool", "String",
    };

    public override bool WriteShortDescription(IDocumentedElement element, LanguageWriter writer, string prefix = "", string suffix = "")
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(element);
        if (!element.Documentation.DescriptionAvailable) return false;
        if (element is not CodeElement codeElement) return false;

        var description = element.Documentation.GetDescription(x => GetTypeReferenceForDocComment(x, codeElement), ReferenceTypePrefix, ReferenceTypeSuffix);
        writer.WriteLine($"{DocCommentPrefix}{description}");

        return true;
    }

    public void WriteParameterDescription(CodeParameter element, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(element);
        var description = element.Documentation.GetDescription(x => GetTypeReferenceForDocComment(x, element), ReferenceTypePrefix, ReferenceTypeSuffix);
        writer.WriteLine($"{DocCommentPrefix}* `{element.Name.ToSnakeCase()}` - {description}");
    }

    public void WriteAutogeneratedMessage(LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(writer);
        writer.WriteLine("// auto-generated by kiota");
    }

    public void WriteLintSuppression(LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(writer);
        writer.WriteLine("#![allow(unused_imports, dead_code, unused_variables, clippy::all)]");
    }

    public void WriteLongDescription(CodeElement element, LanguageWriter writer, IEnumerable<string>? additionalRemarks = default)
    {
        ArgumentNullException.ThrowIfNull(writer);
        if (element is not IDocumentedElement documentedElement || documentedElement.Documentation is not CodeDocumentation documentation) return;
        additionalRemarks ??= [];
        var remarks = additionalRemarks.Where(static x => !string.IsNullOrEmpty(x)).ToArray();
        if (documentation.DescriptionAvailable || documentation.ExternalDocumentationAvailable || remarks.Length != 0)
        {
            if (documentation.DescriptionAvailable)
            {
                var description = documentedElement.Documentation.GetDescription(x => GetTypeReferenceForDocComment(x, element), ReferenceTypePrefix, ReferenceTypeSuffix);
                writer.WriteLine($"{DocCommentPrefix}{description}");
            }
            foreach (var additionalRemark in remarks)
                writer.WriteLine($"{DocCommentPrefix}{additionalRemark}");
            if (element is IDeprecableElement deprecableElement && deprecableElement.Deprecation is not null && deprecableElement.Deprecation.IsDeprecated)
                foreach (var additionalComment in GetDeprecationInformationForDocumentationComment(deprecableElement))
                    writer.WriteLine($"{DocCommentPrefix}{additionalComment}");

            if (documentation.ExternalDocumentationAvailable)
                writer.WriteLine($"{DocCommentPrefix}[{documentation.DocumentationLabel}]({documentation.DocumentationLink})");
        }
    }

    internal string GetTypeReferenceForDocComment(CodeTypeBase code, CodeElement targetElement)
    {
        if (code is CodeType codeType && codeType.TypeDefinition is CodeMethod method)
            return $"{GetTypeString(new CodeType { TypeDefinition = method.Parent, IsExternal = false }, targetElement)}::{GetTypeString(code, targetElement)}";
        return $"{GetTypeString(code, targetElement)}";
    }

    private string[] GetDeprecationInformationForDocumentationComment(IDeprecableElement element)
    {
        if (element.Deprecation is null || !element.Deprecation.IsDeprecated) return Array.Empty<string>();

        var versionComment = string.IsNullOrEmpty(element.Deprecation.Version) ? string.Empty : $" as of {element.Deprecation.Version}";
        var dateComment = element.Deprecation.Date is null ? string.Empty : $" on {element.Deprecation.Date.Value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}";
        var removalComment = element.Deprecation.RemovalDate is null ? string.Empty : $" and will be removed {element.Deprecation.RemovalDate.Value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}";
        return [
            $"# Deprecated",
            $"{element.Deprecation.GetDescription(type => GetTypeString(type, (element as CodeElement)!))}{versionComment}{dateComment}{removalComment}"
        ];
    }

    public override string GetAccessModifier(AccessModifier access)
    {
        return access switch
        {
            AccessModifier.Public => "pub ",
            AccessModifier.Protected => "pub(crate) ",
            AccessModifier.Private => "",
            _ => "pub ",
        };
    }

    internal void AddRequestBuilderBody(CodeClass parentClass, string returnType, LanguageWriter writer, string? urlTemplateVarName = default, string? prefix = default, IEnumerable<CodeParameter>? pathParameters = default, IEnumerable<CodeParameter>? customParameters = default)
    {
        if (parentClass.GetPropertyOfKind(CodePropertyKind.PathParameters) is CodeProperty pathParametersProp &&
            parentClass.GetPropertyOfKind(CodePropertyKind.RequestAdapter) is CodeProperty requestAdapterProp)
        {
            var pathParametersSuffix = !(pathParameters?.Any() ?? false) ? string.Empty :
                $", {string.Join(", ", pathParameters.Select(x => $"{x.Name.ToSnakeCase()}"))}";
            var urlTplRef = string.IsNullOrEmpty(urlTemplateVarName) ? $"self.{pathParametersProp.Name.ToSnakeCase()}.clone()" : urlTemplateVarName;
            if (customParameters?.Any() ?? false)
            {
                urlTplRef = TempDictionaryVarName;
                writer.WriteLine($"let mut {urlTplRef} = self.{pathParametersProp.Name.ToSnakeCase()}.clone();");
                foreach (var param in customParameters)
                    writer.WriteLine($"{urlTplRef}.insert(\"{param.SerializationName}\".to_string(), {param.Name.ToSnakeCase()}.to_string());");
            }
            writer.WriteLine($"{prefix}{returnType}::new({urlTplRef}, self.{requestAdapterProp.Name.ToSnakeCase()}.clone(){pathParametersSuffix})");
        }
    }

    public override string TempDictionaryVarName => "url_tpl_params";

    internal void AddParametersAssignment(LanguageWriter writer, CodeTypeBase pathParametersType, string pathParametersReference, string varName = "", params (CodeTypeBase, string, string)[] parameters)
    {
        if (pathParametersType == null) return;
        if (string.IsNullOrEmpty(varName))
        {
            varName = TempDictionaryVarName;
            writer.WriteLine($"let mut {varName} = {pathParametersReference}.clone();");
        }
        if (parameters.Length != 0)
        {
            writer.WriteLines(parameters.Select(p =>
            {
                var (ct, name, identName) = p;
                var identSnake = identName.ToSnakeCase();
                string nullCheck = string.Empty;
                if (ct.CollectionKind == CodeTypeCollectionKind.None && ct.IsNullable)
                {
                    nullCheck = $"if let Some(val) = &{identSnake} {{ ";
                    return $"{nullCheck}{varName}.insert(\"{name}\".to_string(), val.to_string()); }}";
                }
                return $"{varName}.insert(\"{name}\".to_string(), {identSnake}.to_string());";
            }).ToArray());
        }
    }

    public override string GetTypeString(CodeTypeBase code, CodeElement targetElement, bool includeCollectionInformation = true, LanguageWriter? writer = null)
    {
        return GetTypeString(code, targetElement, includeCollectionInformation, true);
    }

    public string GetTypeString(CodeTypeBase code, CodeElement targetElement, bool includeCollectionInformation, bool includeNullableInformation, bool includeActionInformation = true)
    {
        ArgumentNullException.ThrowIfNull(targetElement);
        if (code is CodeComposedTypeBase)
            throw new InvalidOperationException($"Rust does not support union types, the union type {code.Name} should have been filtered out by the refiner");
        if (code is CodeType currentType)
        {
            var typeName = TranslateType(currentType);

            var collectionWrapper = currentType.CollectionKind != CodeTypeCollectionKind.None && includeCollectionInformation;
            var wrappedType = collectionWrapper ? $"Vec<{typeName}>" : typeName;

            var genericParameters = currentType.GenericTypeParameterValues.Any() ?
                $"<{string.Join(", ", currentType.GenericTypeParameterValues.Select(x => GetTypeString(x, targetElement, includeCollectionInformation)))}>" :
                string.Empty;
            if (!string.IsNullOrEmpty(genericParameters))
                wrappedType = $"{typeName}{genericParameters}";

            if (currentType.ActionOf && includeActionInformation)
                return $"Box<dyn Fn({wrappedType})>";

            if (currentType.IsNullable && includeNullableInformation)
                return $"Option<{wrappedType}>";

            return wrappedType;
        }

        throw new InvalidOperationException($"type of type {code?.GetType()} is unknown");
    }

    public override string TranslateType(CodeType type)
    {
        ArgumentNullException.ThrowIfNull(type);
        return type.Name.ToLowerInvariant() switch
        {
            "integer" or "int32" => "i32",
            "int64" => "i64",
            "sbyte" => "i8",
            "byte" => "u8",
            "boolean" => "bool",
            "string" => "String",
            "float" => "f32",
            "double" or "decimal" => "f64",
            "object" => "serde_json::Value",
            "void" => "()",
            "binary" or "base64" or "base64url" => "Vec<u8>",
            "iparsenode" or "parsenode" => "&dyn ParseNode",
            "iserializationwriter" or "serializationwriter" => "&mut dyn SerializationWriter",
            "requestadapter" or "irequestadapter" => "std::sync::Arc<dyn RequestAdapter + Send + Sync>",
            _ => type.Name.Contains("::", StringComparison.Ordinal) ? type.Name : // qualified types (chrono::DateTime, uuid::Uuid) from refiner replacements
                (type.Name.ToFirstCharacterUpperCase() is string typeName && !string.IsNullOrEmpty(typeName) ? typeName : "serde_json::Value"),
        };
    }

    public bool IsPrimitiveType(string typeName)
    {
        if (string.IsNullOrEmpty(typeName)) return false;
        var cleanName = typeName;
        if (cleanName.StartsWith("Option<", StringComparison.Ordinal))
            cleanName = cleanName[7..];
        cleanName = cleanName.TrimEnd('>');
        return PrimitiveTypes.Contains(cleanName) || cleanName.StartsWith("chrono::", StringComparison.Ordinal);
    }

    public override string GetParameterSignature(CodeParameter parameter, CodeElement targetElement, LanguageWriter? writer = null)
    {
        ArgumentNullException.ThrowIfNull(parameter);
        var parameterType = GetTypeString(parameter.Type, targetElement, true, !parameter.Optional);
        var paramName = parameter.Name.ToSnakeCase();
        if (parameter.Optional && !parameterType.StartsWith("Option<", StringComparison.Ordinal))
            parameterType = $"Option<{parameterType}>";
        return $"{paramName}: {parameterType}";
    }

    internal void WriteDeprecationAttribute(IDeprecableElement element, LanguageWriter writer)
    {
        if (element.Deprecation is null || !element.Deprecation.IsDeprecated) return;

        var versionComment = string.IsNullOrEmpty(element.Deprecation.Version) ? string.Empty : $" as of {element.Deprecation.Version}";
        var dateComment = element.Deprecation.Date is null ? string.Empty : $" on {element.Deprecation.Date.Value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}";
        var removalComment = element.Deprecation.RemovalDate is null ? string.Empty : $" and will be removed {element.Deprecation.RemovalDate.Value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}";
        writer.WriteLine($"#[deprecated(note = \"{element.Deprecation.GetDescription(type => GetTypeString(type, (element as CodeElement)!))}{versionComment}{dateComment}{removalComment}\")]");
    }

    public bool ErrorClassPropertyExistsInSuperClass(CodeProperty codeElement)
    {
        return codeElement?.Parent is CodeClass parentClass && parentClass.IsErrorDefinition && ErrorClassProperties.Contains(codeElement.Name);
    }
}
