<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>Latest</LangVersion>
    <TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
    <PackAsTool>true</PackAsTool>
    <PackageIconUrl>http://go.microsoft.com/fwlink/?LinkID=288890</PackageIconUrl>
    <PackageProjectUrl>https://github.com/microsoft/kiota</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ToolCommandName>kiota</ToolCommandName>
    <Authors>Microsoft</Authors>
    <Company>Microsoft</Company>
    <Title>Microsoft.OpenApi.Kiota</Title>
    <PackageId>Microsoft.OpenApi.Kiota</PackageId>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <VersionPrefix>1.35.0</VersionPrefix>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <PackageReleaseNotes>
      https://github.com/microsoft/kiota/releases
    </PackageReleaseNotes>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/microsoft/kiota</RepositoryUrl>
    <Description>OpenAPI based client generator.</Description>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageTags>OpenAPI .NET CSharp TypeScript Java Go PHP Python REST API</PackageTags>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\Microsoft.OpenApi.snk</AssemblyOriginatorKeyFile>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <!-- the source generators emit warnings -->
    <NoWarn>$(NoWarn);CS8785;NU5048;NU5104</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kiota.Builder\Kiota.Builder.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="StreamJsonRpc" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <ProjectReference Include="..\Kiota.Generated\KiotaGenerated.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
