using System;
using System.IO;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;
using Kiota.Builder.Writers.Java;

using Xunit;

namespace Kiota.Builder.Tests.Writers.Java;

public sealed class CodeClassDeclarationWriterTests : IDisposable
{
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeClassDeclarationWriter codeElementWriter;
    private readonly CodeClass parentClass;

    public CodeClassDeclarationWriterTests()
    {
        codeElementWriter = new CodeClassDeclarationWriter(new JavaConventionService());
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.Java, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        var root = CodeNamespace.InitRootNamespace();
        parentClass = new()
        {
            Name = "parentClass"
        };
        root.AddClass(parentClass);
    }
    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }
    [Fact]
    public void WritesSimpleDeclaration()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("public class", result);
    }
    [Fact]
    public void WritesAutoGeneratedHeader()
    {
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains(JavaConventionService.AutoGenerationHeader, result);
    }
    [Fact]
    public void WritesImplementation()
    {
        var declaration = parentClass.StartBlock;
        declaration.AddImplements(new CodeType
        {
            Name = "someInterface"
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.Contains("implements", result);
    }
    [Fact]
    public void WritesInheritance()
    {
        var declaration = parentClass.StartBlock;
        declaration.Inherits = new()
        {
            Name = "someInterface"
        };
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.Contains("extends", result);
    }
    [Fact]
    public void WritesImports()
    {
        var declaration = parentClass.StartBlock;
        declaration.AddUsings(new()
        {
            Name = "Objects",
            Declaration = new()
            {
                Name = "java.util",
                IsExternal = true,
            }
        },
        new()
        {
            Name = "project.graph",
            Declaration = new()
            {
                Name = "Message",
            }
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.Contains("import project.graph.Message", result);
        Assert.Contains("import java.util.Objects", result);
    }
    [Fact]
    public void RemovesImportWithClassName()
    {
        var declaration = parentClass.StartBlock;
        declaration.AddUsings(new CodeUsing
        {
            Name = "project.graph",
            Declaration = new()
            {
                Name = "parentClass",
            }
        });
        codeElementWriter.WriteCodeElement(declaration, writer);
        var result = tw.ToString();
        Assert.DoesNotContain("project.graph.parentClass", result);
    }
    [Fact]
    public void WritesGenericDeclaration()
    {
        parentClass.StartBlock.AddTypeParameter(new CodeTypeParameter { Name = "TItemType" });
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("public class parentClass<TItemType extends Parsable>", result);
    }
    [Fact]
    public void WritesGenericDerivedConstructorForwardingToGenericBase()
    {
        var itemTypeParameter = new CodeTypeParameter { Name = "TItemType" };
        parentClass.StartBlock.AddTypeParameter(itemTypeParameter);
        var baseClass = new CodeClass { Name = "BasePage" };
        baseClass.StartBlock.AddTypeParameter(new CodeTypeParameter { Name = "TItemType" }); // the base owns its parameter instance
        var inherits = new CodeType { TypeDefinition = baseClass };
        inherits.AddGenericTypeParameterValue(new CodeType { TypeDefinition = parentClass.TypeParameters[0] }); // derived closes over its own parameter
        parentClass.StartBlock.Inherits = inherits;
        parentClass.AddProperty(new CodeProperty
        {
            Name = "page",
            Type = new CodeType { Name = "int", IsExternal = true },
        });
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("public class parentClass<TItemType extends Parsable> extends BasePage<TItemType>", result);
        Assert.Contains("public parentClass(@jakarta.annotation.Nonnull final ParsableFactory<TItemType> itemTypeFactory) {", result);
        Assert.Contains("super(itemTypeFactory);", result);
        // the derived class deserializes no TItemType property of its own, the base owns the factory field
        Assert.DoesNotContain("_itemTypeFactory", result);
    }
    [Fact]
    public void WritesFactoryFieldOnlyForOwnDeserializers()
    {
        var itemTypeParameter = new CodeTypeParameter { Name = "TItemType" };
        parentClass.StartBlock.AddTypeParameter(itemTypeParameter);
        var itemsType = new CodeType { TypeDefinition = itemTypeParameter, CollectionKind = CodeTypeBase.CodeTypeCollectionKind.Complex };
        parentClass.AddProperty(new CodeProperty
        {
            Name = "items",
            Type = itemsType,
        });
        codeElementWriter.WriteCodeElement(parentClass.StartBlock, writer);
        var result = tw.ToString();
        Assert.Contains("private final ParsableFactory<TItemType> _itemTypeFactory;", result);
        Assert.Contains("this._itemTypeFactory = itemTypeFactory;", result);
    }
}
