# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://rubygems.pkg.github.com/microsoft" }

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_abstractions", "0.1.0"
end

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', require: false

gem 'uuidtools'
