/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MoveType, MoveTypeObject } from '../models/';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /play
 */
export interface PlayRequestBuilder extends BaseRequestBuilder<PlayRequestBuilder> {
    /**
     * Play a move
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MoveType>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MoveType | undefined>;
    /**
     * Play a move
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlayRequestBuilderUriTemplate = "{+baseurl}/play";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlayRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PlayRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendEnum",
        enumObject: MoveTypeObject,
    },
};
/* tslint:enable */
/* eslint-enable */
