// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kiota.Builder.SearchProviders.GitHub.GitHubClient.Models
{
    /// <summary>The level of permission to grant the access token to view and manage interaction limits on a repository.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AppPermissions_interaction_limits
    {
        [EnumMember(Value = "read")]
        #pragma warning disable CS1591
        Read,
        #pragma warning restore CS1591
        [EnumMember(Value = "write")]
        #pragma warning disable CS1591
        Write,
        #pragma warning restore CS1591
    }
}
