// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kiota.Builder.SearchProviders.GitHub.GitHubClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContentSubmodule_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "submodule")]
        #pragma warning disable CS1591
        Submodule,
        #pragma warning restore CS1591
    }
}
