// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kiota.Builder.SearchProviders.GitHub.GitHubClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum ContentSymlink_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "symlink")]
        #pragma warning disable CS1591
        Symlink,
        #pragma warning restore CS1591
    }
}
