// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Kiota.Builder.SearchProviders.GitHub.GitHubClient.Models
{
    /// <summary>State of the release asset.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReleaseAsset_state
    {
        [EnumMember(Value = "uploaded")]
        #pragma warning disable CS1591
        Uploaded,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
    }
}
