# frozen_string_literal: true

source 'https://rubygems.org'
source "https://rubygems.pkg.github.com/microsoft"

# Specify your gem's dependencies in microsoft_kiota_authentication.gemspec
gemspec

# gem "microsoft_kiota_abstractions", path: "../../../../abstractions/ruby/microsoft_kiota_abstractions"

