# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in microsoft_kiota_authentication.gemspec
gemspec

# git_source(:github) { |repo_name| "https://rubygems.pkg.github.com/microsoft" }

source "https://rubygems.pkg.github.com/microsoft" do
  gem "microsoft_kiota_abstractions", '0.4.0'
end

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'rubocop', require: false

gem 'addressable', '~> 2.7', '>= 2.7.0'

gem "oauth2", "~> 2.0"
