// <auto-generated/>
#pragma warning disable CS0618
using Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.Contents;
using Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.Releases;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRepoItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The contents property</summary>
        public global::Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.Contents.ContentsRequestBuilder Contents
        {
            get => new global::Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.Contents.ContentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releases property</summary>
        public global::Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.Releases.ReleasesRequestBuilder Releases
        {
            get => new global::Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.Releases.ReleasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.WithRepoItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepoItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.Builder.SearchProviders.GitHub.GitHubClient.Repos.Item.Item.WithRepoItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepoItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
