// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models {
    /// <summary>Describes the state of an artifact or artifact version.  The following statesare possible:* ENABLED* DISABLED* DEPRECATED</summary>
    public enum ArtifactState {
        [EnumMember(Value = "ENABLED")]
        ENABLED,
        [EnumMember(Value = "DISABLED")]
        DISABLED,
        [EnumMember(Value = "DEPRECATED")]
        DEPRECATED,
    }
}
