// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models {
    public enum SortBy {
        [EnumMember(Value = "name")]
        Name,
        [EnumMember(Value = "createdOn")]
        CreatedOn,
    }
}
