# frozen_string_literal: true

require_relative "microsoft_kiota_abstractions/authentication/authentication_provider"
require_relative "microsoft_kiota_abstractions/authentication/base_bearer_token_authentication_provider"
require_relative "microsoft_kiota_abstractions/authentication/anonymous_authentication_provider"
require_relative "microsoft_kiota_abstractions/api_error"
require_relative "microsoft_kiota_abstractions/http_method"
require_relative "microsoft_kiota_abstractions/api_client_builder"
require_relative "microsoft_kiota_abstractions/request_adapter"
require_relative "microsoft_kiota_abstractions/request_option"
require_relative "microsoft_kiota_abstractions/request_headers"
require_relative "microsoft_kiota_abstractions/request_information"
require_relative "microsoft_kiota_abstractions/version"
require_relative "microsoft_kiota_abstractions/serialization/parsable"
require_relative "microsoft_kiota_abstractions/serialization/iso_duration"
require_relative "microsoft_kiota_abstractions/serialization/additional_data_holder"
require_relative "microsoft_kiota_abstractions/serialization/parse_node"
require_relative "microsoft_kiota_abstractions/serialization/parse_node_factory"
require_relative "microsoft_kiota_abstractions/serialization/parse_node_factory_registry"
require_relative "microsoft_kiota_abstractions/serialization/serialization_writer"
require_relative "microsoft_kiota_abstractions/serialization/serialization_writer_factory"
require_relative "microsoft_kiota_abstractions/serialization/serialization_writer_factory_registry"

module MicrosoftKiotaAbstractions
end
