/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.microsoft.kiota;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OkHttpCoreTest {
    @Test void testSomeOkHttpCoreMethod() {
        OkHttpCore classUnderTest = new OkHttpCore();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
