# frozen_string_literal: true

require_relative "microsoft_kiota_authentication_oauth/version"
require_relative "microsoft_kiota_authentication_oauth/contexts/authorization_code_context"
require_relative "microsoft_kiota_authentication_oauth/contexts/client_credential_context"
require_relative "microsoft_kiota_authentication_oauth/contexts/on_behalf_of_context"
require_relative "microsoft_kiota_authentication_oauth/contexts/oauth_context"
require_relative "microsoft_kiota_authentication_oauth/contexts/oauth_custom_flow"
require_relative "microsoft_kiota_authentication_oauth/extensions/oauth2_ext"
require_relative "microsoft_kiota_authentication_oauth/oauth_access_token_provider"
require_relative "microsoft_kiota_authentication_oauth/oauth_authentication_provider"

module MicrosoftKiotaAuthenticationOAuth
end
