/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota

export type MoveType = (typeof MoveTypeObject)[keyof typeof MoveTypeObject];
export const MoveTypeObject = {
    ROCK: "ROCK",
    PAPER: "PAPER",
    SCISSORS: "SCISSORS",
} as const;
/* tslint:enable */
/* eslint-enable */
