/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.microsoft.kiota.http;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OkHttpRequestAdapterTest {
    @Test void testSomeHttpCoreMethod() {
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
