/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.microsoft.kiota.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HttpCoreTest {
    @Test void testSomeHttpCoreMethod() {
        HttpCore classUnderTest = new HttpCore();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
