AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Lint/Void:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/IndentationStyle:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false