AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/TrailingWhitespace:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Lint/Void:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false