name: Deploy kiota.dev
on:
  push:
    tags: ["v*"]

jobs:
  publish_kiota_dev:
    name: Publish kiota.dev
    environment:
      name: kiota.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore workloads
        run: |
          dotnet workload restore
          dotnet workload install wasm-tools
      - name: Publish kiota.dev
        run: dotnet publish -c Release
        working-directory: ./src/Kiota.Web

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        name: Azure Blob Upload with Destination folder defined
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: "$web"
          source_folder: src/Kiota.Web/bin/Release/net7.0/publish/wwwroot
          delete_if_exists: true
